"""
Overview dashboard charts: Segment distributions, revenue breakdown, and share analysis.
"""

from typing import Optional
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

from config.settings import SEGMENT_COLORS


def segment_customer_bar(labeled_df: pd.DataFrame) -> go.Figure:
    """
    Bar chart of customer counts per segment, sorted by count.
    """
    counts = (
        labeled_df.groupby("segment")
        .size()
        .reset_index(name="customer_count")
        .sort_values(by="customer_count", ascending=True)
    )
    total = len(labeled_df)
    counts["percentage"] = (counts["customer_count"] / total * 100).round(1)

    fig = px.bar(
        counts,
        x="customer_count",
        y="segment",
        orientation="h",
        text=counts.apply(lambda r: f"{r['customer_count']:,} ({r['percentage']}%)", axis=1),
        color="segment",
        color_discrete_map=SEGMENT_COLORS,
        labels={"customer_count": "Customers", "segment": "Segment"},
        title="Customer Distribution by Segment",
    )
    fig.update_layout(
        showlegend=False,
        margin=dict(l=20, r=40, t=50, b=20),
        xaxis_title="Number of Customers",
        yaxis_title="",
        hovermode="closest",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
    )
    fig.update_traces(textposition="outside", cliponaxis=False)
    return fig


def segment_revenue_bar(labeled_df: pd.DataFrame) -> go.Figure:
    """
    Bar chart of total revenue generated per segment.
    """
    rev = (
        labeled_df.groupby("segment")["monetary"]
        .sum()
        .reset_index()
        .sort_values(by="monetary", ascending=True)
    )
    total_rev = labeled_df["monetary"].sum()
    rev["percentage"] = (rev["monetary"] / total_rev * 100).round(1) if total_rev > 0 else 0.0

    fig = px.bar(
        rev,
        x="monetary",
        y="segment",
        orientation="h",
        text=rev.apply(lambda r: f"${r['monetary']:,.0f} ({r['percentage']}%)", axis=1),
        color="segment",
        color_discrete_map=SEGMENT_COLORS,
        labels={"monetary": "Total Revenue ($)", "segment": "Segment"},
        title="Revenue Generated by Segment",
    )
    fig.update_layout(
        showlegend=False,
        margin=dict(l=20, r=40, t=50, b=20),
        xaxis_title="Total Spend ($)",
        yaxis_title="",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
    )
    fig.update_traces(textposition="outside", cliponaxis=False)
    return fig


def segment_treemap(labeled_df: pd.DataFrame) -> go.Figure:
    """
    Treemap displaying segment market share by customer volume and revenue.
    """
    summary = (
        labeled_df.groupby("segment")
        .agg(
            customers=("customer_id", "count"),
            revenue=("monetary", "sum"),
            avg_recency=("recency", "mean"),
            avg_frequency=("frequency", "mean"),
        )
        .reset_index()
    )
    summary["avg_spend_per_cust"] = (summary["revenue"] / summary["customers"]).round(2)
    summary["revenue"] = summary["revenue"].round(2)

    fig = px.treemap(
        summary,
        path=["segment"],
        values="customers",
        color="segment",
        color_discrete_map=SEGMENT_COLORS,
        hover_data={"revenue": ":$,.2f", "avg_spend_per_cust": ":$,.2f", "avg_frequency": ":.1f", "avg_recency": ":.0f"},
        title="Segment Breakdown (Size = Customer Count)",
    )
    fig.update_layout(
        margin=dict(l=10, r=10, t=40, b=10),
        paper_bgcolor="rgba(0,0,0,0)",
    )
    return fig


def rfm_summary_scatter(labeled_df: pd.DataFrame) -> go.Figure:
    """
    2D bubble scatter: Recency vs Monetary with Frequency as bubble size.
    """
    plot_df = labeled_df.copy()
    # Guard against $0.00 spend producing -inf on log_y scale: clip minimum monetary to $0.01
    plot_df["monetary"] = plot_df["monetary"].clip(lower=0.01)

    fig = px.scatter(
        plot_df,
        x="recency",
        y="monetary",
        size="frequency",
        color="segment",
        color_discrete_map=SEGMENT_COLORS,
        hover_name="customer_id",
        hover_data={
            "recency": True,
            "frequency": True,
            "monetary": ":$,.2f",
            "segment": True,
        },
        labels={
            "recency": "Recency (Days since last purchase)",
            "monetary": "Monetary ($ Total Spend)",
            "frequency": "Frequency (Orders)",
        },
        title="Customer Value Landscape (Recency vs Monetary)",
        size_max=30,
        log_y=True,
    )
    fig.update_layout(
        legend_title_text="Segment",
        margin=dict(l=20, r=20, t=50, b=20),
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
    )
    return fig
